# Version of docker-compose.
version: "3"

# Containers we're going to run.
services:
  # Our Phoenix container.
  phoenix:
    # The build parameters for this container.
    build:
      # Here we define that it should build from the current directory.
      context: .
    environment:
      # Variables to connect to our Postgres server.
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: postgres
      DB_PORT: 5432
      DB_HOST: db
      PHX_SERVER: true
      PHX_HOST: 0.0.0.0
      SECRET_KEY_BASE: wZ2LZxcKq3d2UkJMQEyvwB/WLCsKnDUgcwPFwulU3z8ofrUWLGfeFqR84iwjzgd3
    ports:
      # Mapping the port to make the Phoenix app accessible outside of the container.
      - "4000:4000"
    depends_on:
      # The DB container needs to be started before we start this container.
      - db
    networks:
      - funds_jet_net
  db:
    # We use the predefined Postgres image.
    image: postgres:14.12
    environment:
      # Set user/password for Postgres.
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      # Set a path where Postgres should store the data.
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - funds_jet_net
# Define the volumes.
volumes:
  pgdata:
networks:
  funds_jet_net:
