# Version of docker-compose.
version: "3"

# Containers we're going to run.
services:
  # Our Phoenix container.
  phoenix:
    # The build parameters for this container.
    build:
      # Here we define that it should build from the current directory.
      context: .
    environment:
      # Variables to connect to our Postgres server.
      DB_USER: fundsjet_dev
      DB_PASS: fundsjet_dev
      DB_NAME: fundsjet_dev
      DB_PORT: 54321
      DB_HOST: db
    ports:
      # Mapping the port to make the Phoenix app accessible outside of the container.
      - "4000:4000"
    depends_on:
      # The DB container needs to be started before we start this container.
      - db
  db:
    # We use the predefined Postgres image.
    image: postgres:14:12
    environment:
      # Set user/password for Postgres.
      POSTGRES_USER: fundsjet_dev
      POSTGRES_PASSWORD: fundsjet_dev
      POSTGRES_DB: fundsjet_dev
      # Set a path where Postgres should store the data.
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    ports:
      - "54321:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
# Define the volumes.
volumes:
  pgdata:
